services:

    Shopping\ApiFilterBundle\Service\ApiService:
        autowire: true
        public: true

    Shopping\ApiFilterBundle\EventListener\AnnotationListener:
        autowire: true
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Shopping\ApiFilterBundle\Describer\AnnotationDescriber:
        autowire: true
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@nelmio_api_doc.controller_reflector'
        tags:
            - {name: 'nelmio_api_doc.route_describer', priority: -2000 }

    Shopping\ApiFilterBundle\ParamConverter\ResultConverter:
        autowire: true
        tags:
            - { name: request.param_converter }