services:

    Shopping\ApiTKUrlBundle\Service\ApiService:
        autowire: true
        public: true

    Shopping\ApiTKUrlBundle\EventListener\AnnotationListener:
        autowire: true
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Shopping\ApiTKUrlBundle\Describer\AnnotationDescriber:
        autowire: true
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@nelmio_api_doc.controller_reflector'
        tags:
            - {name: 'nelmio_api_doc.route_describer', priority: -2000 }

    Shopping\ApiTKUrlBundle\ParamConverter\ResultConverter:
        autowire: true
        tags:
            - { name: request.param_converter }