services:

    Ofeige\Rfc14Bundle\Service\Rfc14Service:
        autowire: true
        public: true

    Ofeige\Rfc14Bundle\EventListener\AnnotationListener:
        autowire: true
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Ofeige\Rfc14Bundle\EventListener\PaginationResponseListener:
        autowire: true
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    Ofeige\Rfc14Bundle\Describer\AnnotationDescriber:
        autowire: true
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@nelmio_api_doc.controller_reflector'
        tags:
            - {name: 'nelmio_api_doc.route_describer', priority: -2000 }